version: "3.8"
services:
  reverse-proxy:
    # 官方的 traefik v2 docker 镜像
    image: traefik:v2.2
    # 启用 web UI，并告诉Traefik侦听docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # HTTP 端口映射
      - "80:80"
      # traefik Web UI 端口映射(enable by --api.insecure=true)
      - "8080:8080"
    volumes:
      # 以便Traekit能够监听Docker事件
      - /var/run/docker.sock:/var/run/docker.sock
  account:
    build:
      context: ./account
      target: builder
    image: account
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`malcorp.test`) && PathPrefix(`/api/account`)"
    environment:
      - ENV=dev
    volumes:
      - ./account:/go/src/app
    tty: true
    # 必须使用$$(双美元符号)，这样docker就不会尝试替换变量
    command: reflex -r '\.go$$' -s -- sh -c 'go run ./'
